<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find engineer_description)/urdf/robot/engineer_roller.gazebo"/>

  <xacro:property name="wheel_radius" value="0.066957864" />>

  <xacro:macro name="engineer_roller" params="prefix parent origin_z rotation_x rotation_z">
    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${wheel_radius * cos(rotation_z)} ${wheel_radius * sin(rotation_z)} ${origin_z}" rpy="${rotation_x} 0 ${rotation_z}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find engineer_description)/meshes/roller.STL" />
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find engineer_description)/meshes/roller.STL" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.008738" />
        <inertia ixx="0.000001" ixy="0" ixz="0"
                 iyy="0.000001" iyz="0" izz="0.000001" />
      </inertial>
    </link>
  </xacro:macro>

</robot>
